### ISSUE TITLE
TOTO LETTER WA (U+1E29C): incorrect dot below to be replaced by a breathy accent below

### ISSUE THREAD

**Issue by verdy-p** [notofonts/toto#3]
### Title 
TOTO LETTER WA (U+1E29C): incorrect dot below to be replaced by a breathy accent below

### Font 
* Noto Serif Toto Regular
* Noto Serif Toto Medium
* Noto Serif Toto SemiBold
* Noto Serif Toto Bold
* Noto Serif Toto [variable wght]

### Where the font came from, and when
* Site: https://fonts.google.com/noto/specimen/Noto+Serif+Toto; Date: 2023-12-25
### Font Version
* 2.001

### Issue

U+1E29C TOTO LETTER WA

The diacritic rendered here (below the base glyph used for Toto letter LA U+1E2A0) is incorrect:
* It should not be a dot, as shown here (this may cause confusion with Toto letter PA U+1E290, which correctly uses a central dot).
* it should be the same as the diacritic used below breathy vowels (U+1E2A2, U+1E2A4, U+1E2A7, U+1E2A9, U+1E2AC), i.e. similar to a grave accent below (but drawn backward from bottom right to top-left), as shown in reference charts:
  https://www.unicode.org/charts/PDF/U1E290.pdf
  https://www.unicode.org/charts/fr/PDF/U1E290.pdf
  https://scriptsource.org/cms/scripts/page.php?item_id=script_detail_sym&key=Toto

See also references present in the proposal to encode the script in Unicode:
*   https://www.unicode.org/L2/L2019/19278-toto-script.pdf
  (Note that the early proposal to encode TOTO SIGN BREATHINESS in the UCS was NOT retained; the sign was described as being used only on some vowels with this meaning, not productive anywhere else, so breathy vowels were finally encoded only in a non-decomposable way; the diacritical glyph looking identical below consonant LA to turn it into a WA does not conflict with any composition).

There's no evidence from any sources (known by Unicode or ISO for the encoding process, or relevant from the originating area in India) showing that the dot below is a valid variant of the breathy accent. Instead using a dot may cause confusion with letter PA (especially at small font sizes where the dot may need to be slightly moved down), which correctly uses a dot diacritic on the base glyph for consonnant LA (the exact placement and form of the central dot, used for letters PA, IU and breathy IU, may eventually vary a bit around the middle of the base glyph). The only "evidences" have originated only from documented created after the release of this early/unfixed Noto font using a creative reinterpretation or just an error from the initial creator (whose work was not reviewed independantly).

Note that dots used on Unicode and scriptsource.org reference Toto charts is rectangular, but Noto Serif Toto uses rounded dots: this is not a critical bug as this does not create any confusion (but in a "serif" font, the square form should be preferable, the rounded dot is probably for a sans-serif font family, still to be created).

Note also that this font still has other issues detected on Fontbakery (for qa/shapingtests), with non-optimal shapes and some broken metadata, plus missing/incorrect metadata issues for the variable font version (https://googlefonts.github.io/gf-guide/variable): this is still not an issue in this repository, but used downstream for releases in Google fonts after passing quality tests (despite these tests failed, the initial font version was made available in Google Fonts release...).
* https://notofonts.github.io/toto/

### Screenshot

![image](https://github.com/notofonts/toto/assets/1387035/89cfdf13-cee1-44fd-b738-e95c2cf3c749)

![image](https://github.com/notofonts/toto/assets/1387035/8957c9ea-b6ff-48cd-8745-37f9ac1a56e1)

**Comment by simoncozens** [comment]
Thank you for the report, this will be fixed in the next release!

**Comment by Toby-3-Strands** [comment]
I'm requesting the change from this to be reverted. See https://github.com/notofonts/toto/issues/6

**Comment by verdy-p** [comment]
This should be reported to the UTC and ISO, to investigate the case about its representative glyph in the Unicode and ISO charts. A single report by a font designer using this manual writing, and interpretation of this draft may not be enough. The UTC and ISO have also their own experts that approved the existing letter form. If a dot must should used (independantly of its interpretation as meaning "breathy" or not), this should be discussed there (as well as if /w/ is phonetically perceived as a consonant or a vowel).
May be the dot is an acceptable variant.
