### ISSUE TITLE
Lack of meta table, missing version update after fixing and closing bug #3 (and converting glyph data to the new format)..

### ISSUE THREAD

**Issue by verdy-p** [notofonts/toto#4]
### Title 
  * Lack of meta table, missing version update after fixing and closing bug #3 (and converting glyph data to the new format)..

### Where the font came from, and when
  * this repository (https://github.com/notofonts/toto), deployed 2023-12-28 on [gh-pages](https://github.com/notofonts/toto/tree/gh-pages).

### Issue
  * This font file still does not have a 'meta' table. [code: lacks-meta-table]. Necessary to get proper coverage (not assuming it covers ISO8859-1 and basic diacritics, this should avoid other warnings, like those related to numeric figures, common punctuation or math signs).
  * Lack of updated version (still declares version 2.001 from the current release).
  * initial author/source (Monotype) was dropped, but most glyphs are kept (just converted to a new syntax and extended to use variant axis, and one glyph was significantly modified). Is that intentional?
  * Regression?: Placement of the combining TONE SIGN over the DOTTED CIRCLE was moved to the right (no longer centered). This apparently also changes the maximum width metrics; mark-to-mark positioning no longer works correctly (this was fixed in a prior bug report #2), or there's a missing table in the new converted format.

**Comment by simoncozens** [comment]
Versions are updated when a font is released; you're looking at a pre-release, so obviously it does not have a new version.

The lack of a meta table is not relevant; it's not required to "get coverage" of anything, and I'm not aware of any applications which actually read dlng/slng. Are you?

The change in designer is weird, and should be checked.

One glyph was significantly modified, yes. This is because you asked me to modify it.

**Comment by verdy-p** [comment]
Yes but:
* coverage is part of qa tests (not just dlng/slng, also legacy OS/2 and Microsoft flags for compatibility and allowing proper selection of fonts in applications, including browsers and word processors), may be some meta for MacOS), this is in small tables to add or update, the tests require it otherwise the font will no longer pass the new requirements for next release
* (at that time only you'll need a new font version number but at least it should contain an ".alpha" or ".dev" suffix to the current version number (here again this avoids failing on existing comparison tests), even if you drop that suffix and increment the version in the release.

And you did not address:
* what about the author/sources and licencing being dropped from metadata after the conversions to Glyph format 3?
* what about the regression on mark-to-mark with the dotted circle base?

**Comment by simoncozens** [comment]
> coverage is part of qa tests (not just dlng/slng, also legacy OS/2 and Microsoft flags for compatibility and allowing proper selection of fonts in applications, including browsers and word processors), may be some meta for MacOS), this is in small tables to add or update, the tests require it otherwise the font will no longer pass the new requirements for next release

I'm well aware of the requirements, and I know that we don't worry about certain WARNs - meta table is one of them. The OS/2 and Microsoft flags are fine, there are [no errors](https://notofonts.github.io/toto/fontbakery/notofonts-NotoSerifToto-googlefonts-report.html) for them. And if there are failing checks at release time, then I fix them - that's part of the release process.

> (at that time only you'll need a new font version number but at least it should contain an ".alpha" or ".dev" suffix to the current version number (here again this avoids failing on existing comparison tests), even if you drop that suffix and increment the version in the release.

Well, there are various ways of handling version bumps in software in active development in git repositories. Some people add a .dev suffix, but actually most don't. If I build Python from git today it will claim to be version 3.13.0a2, even though there have been thousands of commits since that version. The way we've chosen here is to bump the version on release.

> what about the author/sources and licencing being dropped from metadata after the conversions to Glyph format 3?

They were not dropped:

```
$ ttx -o - -t name master_ttf/NotoSerifToto-Regular.ttf
Dumping "master_ttf/NotoSerifToto-Regular.ttf" to "<stdout>"...
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.45">

Dumping 'name' table...
  <name>
...
    <namerecord nameID="8" platformID="3" platEncID="1" langID="0x409">
      Monotype Imaging Inc.
    </namerecord>
    <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
      Monotype Design Team
    </namerecord>
    <namerecord nameID="10" platformID="3" platEncID="1" langID="0x409">
      Designed by Monotype design team.
    </namerecord>
    <namerecord nameID="11" platformID="3" platEncID="1" langID="0x409">
      http://www.google.com/get/noto/
    </namerecord>
    <namerecord nameID="12" platformID="3" platEncID="1" langID="0x409">
      http://www.monotype.com/studio
    </namerecord>
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      https://scripts.sil.org/OFL
    </namerecord>
  </name>
```

> what about the regression on mark-to-mark with the dotted circle base?

This one is actually a bug caused by a missing language system, will fix.

**Comment by verdy-p** [comment]
Note that Windows 11 now DOES uses and supports 'dlng' and 'slng' metata in its Settings>Fonts panel. Though there's a bug when it parses them: see https://github.com/MicrosoftDocs/typography-issues/issues/1112

'dlng' and 'slng' are better suited for font selection than the legacy OpenType language tags and the legacy OS/2 table or other proprietary flags previously defined by Apple or Adobe (which only partially indicate coverage, not really a "designed for", or "supported" and have severe weaknesses). Both 'dlg'/'slng' should be defined and prefered now in modern TTF/OTF/TTC fonts, even if there are legacy tables or flags (that should be ignored by applications converted to use 'dlng'/'slng' when they are available; already many apps ignore them, notably web browsers, and have to recreate their own index to correctly support font fallbacks and font collections with coherent renderings and metrics, by more easily selecting the best suitable fonts rather then using fallbacks to other font families and designs for individual characters needed in a script or specific language/script, and then failing to compose correctly additional diacritics).

So I have to disagree with your comment :
"The lack of a meta table is not relevant; it's not required to "get coverage" of anything, and I'm not aware of any applications which actually read dlng/slng. Are you?"

The metatable is the way to go. Legacy tables (or proprietary flags in legacy header tables) are only needed in absence of these meta tables (but they don't work correctly for many cases, there are too many "quirks").

**Comment by simoncozens** [comment]
Thanks, that's useful. I'll make sure that goes into the fontbakery rationale, and we get better tooling for easily adding meta info.

I'm not sure whether the font selection for Toto will be greatly improved by this, however. ;-)
